# Generated by Django 3.0.5 on 2020-10-21 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='course.Topics')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='point',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('point', models.PositiveIntegerField(default=50)),
                ('correct_answer', models.CharField(max_length=5)),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Main_test')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(max_length=10)),
                ('question', models.CharField(max_length=200)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_test', to='course.Test')),
            ],
        ),
    ]
